### PR TITLE
Develop store statement

### PR DESCRIPTION
**Pull request by jnnkB**
Changes:
- Added API classes
- formatted everything using prettier
- Added static link for each statement using hash of statement
- extracted findGetParameter
- removed mock
- added eslint config
- fixed var, let and const
- fixed quotes in jsx

### CODE REVIEW

**Review by gruselhaus — APPROVED** [review]
Formatting Rules, yay 😍

**Comment by jnnkB** [comment]
@gruselhaus Was ändert ea7fabe?

**Comment by gruselhaus** [comment]
> @gruselhaus Was ändert [ea7fabe](https://github.com/Jugendhackt/parteiduell-frontend/commit/ea7fabec47d7ccfdc4540a57f744c99e61aca8ff)?

Rebase von f4aa88b

**Comment by jnnkB** [comment]
ah ok

**Pull request merged**
